version: "2"

services:
  php:
    image: php:7.1.10-apache
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./web:/var/www/html
    links:
      - db

  db:
    image: postgres:10
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: root